version: "3.7"

services:
  service0:
    image: luminous/aliyun-security-updater:version #version改成需要的版本号
    pull_policy: always
    container_name: aliyun-security-updater
    restart: on-failure
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/settings.yml:/settings.yml
      - /data/logs/aliyun-security-updater:/logs
