# 复制本文件并映射到 Docker 容器的/settings.yml
# Aliyun A/K
accessKeyId: XXXXXX
accessKeySecret: XXXXXXX
# 执行时间
cron: "*/30 * * * * ?"
# 获取IP的API (默认值 https://api.kiiiv.com/v1/openapi/other/ip) (需要返回Json默认会读取data部分作为IP)
ipApi: https://api.kiiiv.com/v1/openapi/other/ip
# 获取IP的API返回IP的Json节点名 (默认值 data) (最低版本1.2.0)
responseJsonIpNodeName: "data"
# 重试次数 (默认值 0) (最低版本1.2.0)
retryTimes: 3
# 重试间隔(秒) （默认值 10） (最低版本1.2.0)
retryDelay: 5

# 更新DNS(可配置多条) endpoint(接入点) domainName(目标域名) rr(主机记录)
dns:
  - endpoint: alidns.cn-beijing.aliyuncs.com
    domainName: demo.com
    rr: www
  - endpoint: alidns.cn-beijing.aliyuncs.com
    domainName: xx.com
    rr: www1
# 更新ECS安全组(可配置多条) endpoint(接入点) regionId(区域) securityGroupId(安全组ID) description(访问规则描述)
ecs:
  - endpoint: ecs.cn-beijing.aliyuncs.com
    regionId: cn-beijing
    securityGroupId: sg-XXXXXXXXX
    description: demo
# 更新RDS(可配置多条) endpoint(接入点) dbInstanceId(RDS实例ID) ipArrayName(白名单分组名称)
rds:
  - endpoint: rds.cn-beijing.aliyuncs.com
    dbInstanceId: rm-XXXXXXXXX
    ipArrayName: ip_connect_demo
